module.exports = [
  {
    name: 'Movie', collection: '/api/movies', description: 'A film in the shared, in-memory catalog.',
    fields: [
      { name: 'id', type: 'number', notes: 'Positive integer. Generated by the server; read-only.' },
      { name: 'title', type: 'string', notes: 'Required. 1–200 characters, excluding surrounding whitespace.' },
      { name: 'genre', type: 'string', notes: 'Required. 1–80 characters.' },
      { name: 'year', type: 'number', notes: 'Required integer between 1888 and 2100.' },
      { name: 'rating', type: 'number', notes: 'Required number from 0 to 10.' },
      { name: 'director', type: 'string', notes: 'Required. 1–120 characters.' },
      { name: 'available', type: 'boolean', notes: 'Required. Use the JSON literal true or false.' }
    ]
  },
  {
    name: 'Review', collection: '/api/reviews', description: 'A reader’s review of one movie. One movie can have many reviews.',
    fields: [
      { name: 'id', type: 'number', notes: 'Positive integer. Generated by the server; read-only.' },
      { name: 'movieId', type: 'number', notes: 'Related movie ID. Derived from the nested creation route; preserved on replacement.' },
      { name: 'author', type: 'string', notes: 'Required. 1–100 characters.' },
      { name: 'score', type: 'number', notes: 'Required integer from 1 to 5.' },
      { name: 'comment', type: 'string', notes: 'Required. 1–2,000 characters.' }
    ]
  }
];
